### ISSUE TITLE
track method uses deprecated return_score

### ISSUE THREAD

**Issue by ubaldo** [SiftScience/sift-python#27]
Param is useless. I had to add '?return_action=true' to get the score back in the response

**Comment by philfreo** [comment]
Yep @JohnMcSpedon please update your Python client to actually match what your API expects for synchronous calls. e.g. We shouldn't have to pass a custom `path` with a querystring...

**Comment by fredsadaghiani** [comment]
I'll take this on. I'll have something soon!

**Comment by fredsadaghiani** [comment]
I just released v1.1.2.5. Please take a look @philfreo @ubaldo
