### ISSUE TITLE
track, label, etc

### ISSUE THREAD

**Issue by ubaldo** [SiftScience/sift-python#30]
all this methods return the requests.exceptions.RequestException exception instead of re raising it. Is it intended to be that way, it makes for very impractical API consumption

**Comment by fredsadaghiani** [comment]
Hrm... good point. Perhaps we should just `pass`?

**Comment by zackkitzmiller** [comment]
I think it would be ideal to define Sift exception types in this library and not expose `requests` exceptions to the caller. This makes catching them require the caller either 1. import `requests` or 2. catch naked/unnamed exceptions. 

I'm much prefer to do something like

```python
try:
    client.XXX
except sift.ReadTimeout
   # handle here
```

If this is interest in this I could propose a PR.

**Comment by fredsadaghiani** [comment]
Yeah, I like that. Please do!

**Comment by zackkitzmiller** [comment]
@fredsadaghiani Sounds good. Might take me a couple of days to get to it.

**Comment by fredsadaghiani** [comment]
@zackkitzmiller FYI, for now I've updated the code to swallow exceptions. See https://github.com/SiftScience/sift-python/pull/34
