### ISSUE TITLE
TypeError: Decimal('12150.0') is not JSON serializable

### ISSUE THREAD

**Issue by steinbachr** [SiftScience/sift-python#38]
can't pass decimal values when tracking events. Would be nice if the sift client used a custom encoder, as described in this SO post: http://stackoverflow.com/questions/1960516/python-json-serialize-a-decimal-object

**Comment by neoecos** [comment]
+1

**Comment by quanpod** [comment]
@steinbachr Apologies for the long delay here - we're taking a look here.  If you've got a custom implementation that forks from ours, let us know if you want to contribute that modification.

**Comment by ehrmann** [comment]
We could use https://stackoverflow.com/a/1960649/1076480
