### ISSUE TITLE
Documentation link doesn't work

### ISSUE THREAD

**Issue by uvyuhin** [SiftScience/sift-python#50]
Hello,

Link to python documentation returns 404 status: [https://github.com/SiftScience/sift-python/blame/master/README.md#L42]

**Comment by megamannn** [comment]
ahh, sorry about that & thanks for letting us know. I'm submitting an edit so it points to [here](https://siftscience.com/developers/docs/python/events-api/overview) instead.

**Comment by megamannn** [comment]
merged
