### ISSUE TITLE
Don't depend on requests

### ISSUE THREAD

**Issue by cdman** [SiftScience/sift-python#52]
Or at least clearly document this dependency :smile:.

`requests` is complicated to use on Google Appengine since it requires either having a paid account and activating the socket service or using the `requests_toolbelt` package. See:
- https://cloud.google.com/appengine/docs/python/issue-requests
- http://stackoverflow.com/questions/9604799/can-python-requests-library-be-used-on-google-app-engine

Alternatively, if `sift-python` would use libraries which come with the standard library (`urllib2` / `urllib.request`), it would make it easier to use.

**Comment by quanpod** [comment]
Hi @cdman apologies for the long delay here - we're taking a look.  If you've worked around this in the meantime and have updated suggestions, I'd love to hear it.

**Comment by cdman** [comment]
@quanpod - I'm using `request_toolbelt` ([PyPi](https://pypi.python.org/pypi/requests-toolbelt) - [docs](https://toolbelt.readthedocs.io/en/latest/) - [GitHub](https://github.com/requests/toolbelt)) for now (also, because other libraries we use depend on requests), however it has been far from smooth sailing (https://github.com/requests/toolbelt/issues?utf8=%E2%9C%93&q=is%3Aissue%20AppEngine).

IMHO, given the nature of the library, I really think it should only depend on things shipped with Python. But that's just my 2c :-)
