### ISSUE TITLE
sift.client.ApiException: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by StevenLudwig** [SiftScience/sift-python#83]
Hello!

I have the same problem, we are using asynchronous microservices where we are tracking events with Sift sdk with python language, I am controlling the problem with a retry when it fails but the error rate is very high. It looks like the sift sdk is not 'ready' and keeps crashing when still being used... the error trace is coming from the sift sdk connection layer

**Comment by paul-english** [comment]
Same as https://github.com/SiftScience/sift-python/issues/82
